language: php

sudo: false

php:
    - 5.6
    - 7.1
    - 7.2
    - 7.3

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache/files

install:
    - travis_retry composer install --no-interaction --prefer-dist
